/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareRouteImport } from './routes/care'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as MuscularDystrophyRouteImport } from './routes/muscular-dystrophy'
import { Route as PriceListRouteImport } from './routes/price-list'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VolunteerRouteImport } from './routes/volunteer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const MuscularDystrophyRoute = MuscularDystrophyRouteImport.update({
  id: '/muscular-dystrophy',
  path: '/muscular-dystrophy',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceListRoute = PriceListRouteImport.update({
  id: '/price-list',
  path: '/price-list',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/diagnosis': typeof DiagnosisRoute
  '/donate': typeof DonateRoute
  '/facilities': typeof FacilitiesRoute
  '/muscular-dystrophy': typeof MuscularDystrophyRoute
  '/price-list': typeof PriceListRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/shipping': typeof ShippingRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/diagnosis': typeof DiagnosisRoute
  '/donate': typeof DonateRoute
  '/facilities': typeof FacilitiesRoute
  '/muscular-dystrophy': typeof MuscularDystrophyRoute
  '/price-list': typeof PriceListRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/shipping': typeof ShippingRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards': typeof AwardsRoute
  '/blog': typeof BlogRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/diagnosis': typeof DiagnosisRoute
  '/donate': typeof DonateRoute
  '/facilities': typeof FacilitiesRoute
  '/muscular-dystrophy': typeof MuscularDystrophyRoute
  '/price-list': typeof PriceListRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/research': typeof ResearchRoute
  '/shipping': typeof ShippingRoute
  '/stories': typeof StoriesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/volunteer': typeof VolunteerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards'
    | '/blog'
    | '/care'
    | '/contact'
    | '/diagnosis'
    | '/donate'
    | '/facilities'
    | '/muscular-dystrophy'
    | '/price-list'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/research'
    | '/shipping'
    | '/stories'
    | '/support'
    | '/team'
    | '/terms'
    | '/volunteer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards'
    | '/blog'
    | '/care'
    | '/contact'
    | '/diagnosis'
    | '/donate'
    | '/facilities'
    | '/muscular-dystrophy'
    | '/price-list'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/research'
    | '/shipping'
    | '/stories'
    | '/support'
    | '/team'
    | '/terms'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards'
    | '/blog'
    | '/care'
    | '/contact'
    | '/diagnosis'
    | '/donate'
    | '/facilities'
    | '/muscular-dystrophy'
    | '/price-list'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/research'
    | '/shipping'
    | '/stories'
    | '/support'
    | '/team'
    | '/terms'
    | '/volunteer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsRoute: typeof AwardsRoute
  BlogRoute: typeof BlogRoute
  CareRoute: typeof CareRoute
  ContactRoute: typeof ContactRoute
  DiagnosisRoute: typeof DiagnosisRoute
  DonateRoute: typeof DonateRoute
  FacilitiesRoute: typeof FacilitiesRoute
  MuscularDystrophyRoute: typeof MuscularDystrophyRoute
  PriceListRoute: typeof PriceListRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  ResearchRoute: typeof ResearchRoute
  ShippingRoute: typeof ShippingRoute
  StoriesRoute: typeof StoriesRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muscular-dystrophy': {
      id: '/muscular-dystrophy'
      path: '/muscular-dystrophy'
      fullPath: '/muscular-dystrophy'
      preLoaderRoute: typeof MuscularDystrophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-list': {
      id: '/price-list'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof PriceListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsRoute: AwardsRoute,
  BlogRoute: BlogRoute,
  CareRoute: CareRoute,
  ContactRoute: ContactRoute,
  DiagnosisRoute: DiagnosisRoute,
  DonateRoute: DonateRoute,
  FacilitiesRoute: FacilitiesRoute,
  MuscularDystrophyRoute: MuscularDystrophyRoute,
  PriceListRoute: PriceListRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  ResearchRoute: ResearchRoute,
  ShippingRoute: ShippingRoute,
  StoriesRoute: StoriesRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
